#!/usr/bin/env bash
###################################################
# SnapRAID-DAILY
###################################################
# Github Page: https://github.com/zoot101/snapraid-daily
###################################################

# VERSION
version="1.7.2"

###################################################
# VARIABLES
###################################################
max_hooks=5
github_page="https://github.com/zoot101/snapraid-daily"
github_version_file="https://raw.githubusercontent.com/zoot101/snapraid-daily/refs/heads/main/VERSION"

###################################################
# RETURN CODES
###################################################
success_code=0                      # Success
error_code=1                        # All Errors
already_in_use_code=2               # SnapRAID Already in use
files_modified_during_sync_code=3   # Files Modified During Sync
thresholds_exceeded_code=5          # Deletion/Moved Thresholds exceeded

# Modern Error Handling
set -euo pipefail

###################################################
# MAIN FUNCTION
###################################################
main() {

  # Unset All Config Variables
  unset_all_config_variables

  # Parse Input Arguments
  parse_arguments "$@"
  
  # Read & Check Config File, Check for an Update (if enabled) & Check Dependencies
  read_config_file
  check_for_update
  check_dependencies
  
  # Generate Logfiles for Analysis
  generate_logfiles
  
  # Start Email log and print greeting
  print_greeting
 
  # Check the intial status for errors or if touch is needed
  initial_status_check
  
  # Run Start Hook (if given)
  run_start_hooks
 
  # Run Touch if it is required, check for deletion/moved thresholds
  # and then sync the array. Only if the --scrub-only is not selected
  if [[ "${scrub_only}" == "no" ]]; then
    run_touch_if_needed
    check_array_for_changes_and_thresholds
    sync_array
  fi
  
  # Scrub & Check the output for errors if --sync-only is not selected
  if [[ "${sync_only}" == "no" ]]; then
    scrub_array
  fi
  
  # Run End Hook (if given)
  run_end_hooks

  # Generate SMART Report and spin down disks if enabled and running as root or using sudo
  generate_smart_report
  spin_down_hdd_disks

  # Send Final Notification Email if No Errors were detected, clean up
  # /tmp logfiles and exit with success
  notify_of_success
  clean_up_logfiles
  exit $success_code
}

###################################################
# FUNCTIONS
###################################################
# Error Function for Errors that exit immediately
error() {
  log "ERROR:" "$@"
  log ""
  exit $error_code
}

# Function to check if a Variable is a number >= 0
is_number() {
  local number_regex='^[0-9]+$'
  if ! [[ "$1" =~ $number_regex ]]; then
    return 1
  else
    return 0
  fi
}

# Function to check for a valid scrub number
is_valid_scrub_percent_number() {
  local number="$1"

  # Matches: 0.0 to 99.9, 100.0 only
  if [[ "$number" =~ ^(100(\.0)?|([0-9]{1,2}(\.[0-9])?))$ ]]; then
    return 0
  else
    return 1
  fi
}

# Check if a command is available
is_installed() {
  command -v "${1}" &>"/dev/null"
}

# Check content files are writable
check_content_files_exist() {

  # Read the main Configuration file line-by-line
  while IFS= read -r line; do

    # Strip leading whitespace, trailing comment if present & Skip empty lines and comments
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%%#*}"
    if [[ -z "${line}" || "$line" == \#* ]]; then continue; fi
  
    # Only process lines starting with "content"
    if [[ "$line" == content[[:space:]]* ]]; then

      # Remove Content & Trim Leading & Trailing Whitespaces
      content_file="${line#content}"
      content_file="${content_file#"${content_file%%[![:space:]]*}"}"
      content_file="${content_file%"${content_file##*[![:space:]]}"}"

      # Check if the Content File exists & is Writable - if not exit & notify the user.
      # If it does exist, check the ownership and exit if any are not owned by the script user,
      # unless the user has used the -i, --ignore-user option.
      if [[ -w "${content_file}" ]]; then
        if [[ ! -O "${content_file}" && "${ignore_script_user}" == "no" ]]; then
          log_to_email_time "ERROR: SnapRAID Content File: ${content_file} in ${snapraid_config_file_path} is not owned by user: $(whoami)"
          log_to_email_time "Use the -i / --ignore-user option to bypass the ownership check on the SnapRAID Content Files if this is OK"
          log_to_email ""
          notify_of_warning "SnapRAID-DAILY: Content File(s) Error"
          clean_up_logfiles
          exit "$error_code"
        fi
      else
        log_to_email_time "ERROR: SnapRAID Content File: ${content_file} in ${snapraid_config_file_path} not found/writable"
        log_to_email ""
        notify_of_warning "SnapRAID-DAILY: Content File(s) Error"
        clean_up_logfiles
        exit "$error_code"
      fi
    fi
  done < "${snapraid_config_file_path}"
}

###################################################
# LOGGING FUNCTIONS
###################################################
# Log to the Output and the Email (With/Without the Time)
log_to_email() {
  printf '%s\n' "$*" | tee -a "${main_logfile}"
}
log_to_email_time() {
  printf '%s\n' "$(date +%H:%M:%S) : $*" | tee -a "${main_logfile}"
}
log() {
  printf '%s\n' "$*"
}

# Generate the necessary logfiles in /tmp using mktemp
generate_logfiles() {

  # Check to see if one can write to /tmp, try systemd provided $TMPDIR 1st
  TMPDIR="${TMPDIR:-/tmp}"
  if [[ ! -w "${TMPDIR}" ]]; then
    error "${TMPDIR} directory is not writable - Exiting"
  fi

  # Tmp file Prefix - ".txt" added at the end for email attachments
  tmp_file_prefix="snapraid-daily.XXXXX.txt"

  # Generate Logfiles - Export main_logfile to allow hooks to write to it
  main_logfile="$( mktemp -t "${tmp_file_prefix}" )"
  status_command_logfile="$( mktemp -t "${tmp_file_prefix}" )"
  scrub_command_logfile="$( mktemp -t "${tmp_file_prefix}" )"
  sync_command_logfile="$( mktemp -t "${tmp_file_prefix}" )"
  touch_command_logfile="$( mktemp -t "${tmp_file_prefix}" )"
  diff_command_logfile="$( mktemp -t "${tmp_file_prefix}" )"
  export main_logfile

  # Extra Logfiles Required for Inserting Differences in Email Report
  main_logfile_without_diff="$( mktemp -t "${tmp_file_prefix}" )"
  sync_changes_log="$( mktemp -t "${tmp_file_prefix}" )"
  scrub_changes_log="$( mktemp -t "${tmp_file_prefix}" )"
}

##################################################
# SNAPRAID COMMANDS
##################################################
snapraid_status_cmd() {
  # Call Snapraid Status using the "-l" option
  if [[ $quiet_option == "yes" ]]; then
    "${snapraid_binary_path}" -c "${snapraid_config_file_path}" -l "${status_command_logfile}" -qq status &> /dev/null || true
  else
    "${snapraid_binary_path}" -c "${snapraid_config_file_path}" -l "${status_command_logfile}" -qq status || true
  fi
}

snapraid_status_to_email() {
  # Call Snapraid status and pipe the output into the email
  log_to_email "##############################"
  log_to_email "# SnapRAID-DAILY: Array Status"
  log_to_email "##############################"
  log_to_email_time "Current Status of the Array is as below:"
  "${snapraid_binary_path}" -c "${snapraid_config_file_path}" -qq status | tee -a "${main_logfile}" || true
  log_to_email ""
}

# Call Snapraid smart and pipe the output into the email
snapraid_smart_report() {
  local arg="${1:-}"
  if [[ "${arg}" == "non_root" ]]; then
    sudo "${snapraid_binary_path}" -c "${snapraid_config_file_path}" smart | tee -a "${main_logfile}" || true
  else
    "${snapraid_binary_path}" -c "${snapraid_config_file_path}" smart | tee -a "${main_logfile}" || true
  fi
}

# Call Snapraid down to spin down disks
snapraid_spin_down_disks() {
  local arg="${1:-}"
  if [[ "${arg}" == "non_root" ]]; then
    sudo "${snapraid_binary_path}" -c "${snapraid_config_file_path}" down | tee -a "${main_logfile}" || true
  else
    "${snapraid_binary_path}" -c "${snapraid_config_file_path}" down | tee -a "${main_logfile}" || true
  fi
}

# Call snapraid touch to update timestamps. Suppress all output if --quiet option is set
snapraid_touch_cmd() {
  snapraid_touch_args=( -c "${snapraid_config_file_path}" -v -l "${touch_command_logfile}" )
  if [[ $quiet_option == "yes" ]]; then
    snapraid_touch_args+=( -qqqq )
  fi

  # No "|| true" here for touch, as the touch command below requires its return status
  # This is needed as log tags are somewhat limited for the touch operation
  "${snapraid_binary_path}" "${snapraid_touch_args[@]}" touch
}

# Call snapraid diff - Suppress all output if the -q, --quiet option is set
snapraid_diff_cmd() {
  snapraid_diff_args=( -c "${snapraid_config_file_path}" -v -l "${diff_command_logfile}" ) 
  if [[ $quiet_option == "yes" ]]; then
    snapraid_diff_args+=( -qqqq )
  fi
  "${snapraid_binary_path}" "${snapraid_diff_args[@]}" diff || true

  # Get the numbers and exit status from analyzing the command logfile
  number_equal=$( awk -F ":" '/^summary:equal:/ {print $3}' "${diff_command_logfile}")
  number_added=$( awk -F ":" '/^summary:added:/ {print $3}' "${diff_command_logfile}")
  number_removed=$( awk -F ":" '/^summary:removed:/ {print $3}' "${diff_command_logfile}")
  number_updated=$( awk -F ":" '/^summary:updated:/ {print $3}' "${diff_command_logfile}")
  number_moved=$( awk -F ":" '/^summary:moved:/ {print $3}' "${diff_command_logfile}")
  number_copied=$( awk -F ":" '/^summary:copied:/ {print $3}' "${diff_command_logfile}")
  number_relocated=$( awk -F ":" '/^summary:relocated:/ {print $3}' "${diff_command_logfile}")
  number_restored=$( awk -F ":" '/^summary:restored:/ {print $3}' "${diff_command_logfile}")
  diff_exit_status=$( awk -F ":" '/^summary:exit:/ {print $3}' "${diff_command_logfile}")

  # Check if any of the above are undefined, or if the exit status is not expected
  if [[ -z ${number_equal} || -z ${number_added} || -z ${number_removed} || -z ${number_relocated} || \
        -z ${number_updated} || -z ${number_moved} || -z ${number_copied} || \
        -z ${number_copied} || -z ${number_restored} || -z "${diff_exit_status}" ]]; then
    log_to_email_time "Problem with Diff Command - Stopping"
    log_to_email_time "Diff Command Logfile Is attached..."
    log_to_email ""
    run_end_hooks
    notify_of_warning "SnapRAID-DAILY: Diff Warning(s)" "${diff_command_logfile}"
    clean_up_logfiles
    exit $error_code
  elif [[ "${diff_exit_status}" != "diff" && "${diff_exit_status}" != "equal" && \
          "${diff_exit_status}" != "unsynced" ]]; then
    log_to_email_time "Unexpected Exit Status for Diff - Stopping"
    log_to_email_time "It should be either \"diff\", \"equal\" or \"unsynced\""
    log_to_email_time "Diff Command Logfile Is attached..."
    log_to_email ""
    run_end_hooks
    notify_of_warning "SnapRAID-DAILY: Diff Warning(s)" "${diff_command_logfile}"
    clean_up_logfiles
    exit $error_code
  fi    
}

# Call snapraid sync
snapraid_sync_cmd() {
  snapraid_sync_args=( -c "${snapraid_config_file_path}" -v -l "${sync_command_logfile}")

  # Check for force_zero, force_empty, force_uuid, or force_nocopy inputs
  if [[ "${force_zero}" == "yes" ]]; then
    snapraid_sync_args+=( --force-zero )
    log_to_email_time "SYNC WARNING: --force-zero is enabled."
  fi 
  if [[ "${force_empty}" == "yes" ]]; then
    snapraid_sync_args+=( --force-empty )
    log_to_email_time "SYNC WARNING: --force-empty is enabled."
  fi
  if [[ "${force_uuid}" == "yes" ]]; then
    snapraid_sync_args+=( --force-uuid )
    log_to_email_time "SYNC WARNING: --force-uuid is enabled."
  fi

  # Add Pre-Hash Step (On by default), however disable if the force_nocopy is enabled
  if [[ "${sync_pre_hash}" == "yes" ]]; then
    if [[ "${force_nocopy}" == "no" ]]; then
      snapraid_sync_args+=( -h )
    else
      log_to_email_time "SYNC WARNING: Disabling Pre-Hash as force_nocopy is enabled."
    fi
  fi
  if [[ "${force_nocopy}" == "yes" ]]; then
    snapraid_sync_args+=( --force-nocopy )
    log_to_email_time "SYNC WARNING: --force-nocopy is enabled."
  fi
 
  # Suppress all output if the -q, --quiet option is set, then call sync
  if [[ $quiet_option == "yes" ]]; then
    snapraid_sync_args+=( -qqqq )
  fi
  "${snapraid_binary_path}" "${snapraid_sync_args[@]}" sync || true
}

# Call snapraid scrub - suppress output if quiet option is used
snapraid_scrub_cmd() {
  snapraid_scrub_args=( -c "${snapraid_config_file_path}" -v -p "$scrub_percent" -o "$scrub_age" -l "${scrub_command_logfile}" ) 
  if [[ $quiet_option == "yes" ]]; then
    snapraid_scrub_args+=( -qqqq )
  fi
  "${snapraid_binary_path}" "${snapraid_scrub_args[@]}" scrub || true
}

##################################################
# OTHER FUNCTIONS
##################################################

# Unset all Config File Variables
unset_all_config_variables() {

  # Variables from Input Args
  sync_only=
  scrub_only=
  override_thresholds=
  custom_config_file=
  quiet_option=
  disable_touch=
  ignore_script_user=
  force_zero_arg=
  force_empty_arg=
  force_uuid_arg=
  force_nocopy_arg=

  # Greeting Variables
  system_hostname=
  os_name=
  snapraid_version=

  # Main Config File Variables
  snapraid_config_file_path=
  muttrc_path=
  email_address=
  deletion_threshold=
  moved_threshold=
  updated_threshold=
  sync_pre_hash=
  scrub_percent=
  scrub_age=
  disable_emails_on_success=
  include_diff_in_email=
  force_zero=
  force_empty=
  force_uuid=
  force_nocopy=
  snapraid_binary_path=
  disable_update_check=
  smart_report=
  spin_down_disks=
  start_hook1=
  end_hook1=
  notification_hook1=

  # Sync
  hash_errors=
}

# Read Config File parameters in - unset all variables 1st
read_config_file() {

  # Find script directory
  script_directory="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

  # Configuration Files are read in the following order of preference
  # 1 - Custom Config file if specified by the -f or --config options
  # 2 - /etc/snapraid-daily.conf
  # 3 - Same directory as script
  # Exit if none of the above are found
  config_file0="${custom_config_file}"
  config_file1="/etc/snapraid-daily.conf"
  config_file2="${script_directory}""/snapraid-daily.conf"
  if [[ -r "${config_file0}" ]]; then
    log "INFO: Using Config File:" "${config_file0}"
    # shellcheck source=./config/snapraid-daily.conf
    source "${config_file0}"
  elif [[ -r "${config_file1}" ]]; then
    log "INFO: Using Config File:" "${config_file1}"
    # shellcheck source=./config/snapraid-daily.conf
    source "${config_file1}"
  elif [[ -r "${config_file2}" ]]; then
    log "INFO: Using Config File:" "${config_file2}"
    # shellcheck source=./config/snapraid-daily.conf
    source "${config_file2}"
  else
    log "WARNING: No config file found/readable in any of the following locations:"
    log "1. Specified with the -f or --config option"
    log "2: /etc/snapraid-daily.conf"
    log "3: snapraid-daily.conf in script directory:" "${script_directory}"
    log ""
    log "All Defaults will be used"
    log "See the manual entry for snapraid-daily.conf(1)"
    log ""
  fi

  # Check Snapraid Config File Path
  if [[ -z "${snapraid_config_file_path}" ]]; then
    if [[ ! -r "/etc/snapraid.conf" ]]; then
      error "snapraid_config_file_path missing in config and default of /etc/snapraid.conf not found/readable - Exiting"
    else 
      log "WARNING: snapraid_config_file_path not defined in config - Using /etc/snapraid.conf"
      snapraid_config_file_path="/etc/snapraid.conf"
    fi
  elif [[ ! -r "${snapraid_config_file_path}" ]]; then
    error "snapraid_config_file_path:" "${snapraid_config_file_path}" "does not exist or is not readable - Exiting"
  fi

  # Check for a Valid muttrc file and email address. If not found, disable the email functionality
  if [[ -z "${muttrc_path}" || ! -r "${muttrc_path}" ]]; then
    log "WARNING: muttrc_path missing in config, not readable, or doesn't exist - No Emails will be sent"
    enable_emails="no"
  elif [[ -z "${email_address}" ]]; then
    log "WARNING: email_address missing from snapraid-daily.conf - No Emails will be sent"
    enable_emails="no"
  else
    enable_emails="yes"
  fi

  # Check for the Deletion Threshold
  if [[ -z "${deletion_threshold}" ]]; then
    log "WARNING: deletion_threshold not defined in snapraid-daily.conf - Using 100 by default"
    deletion_threshold=100
  elif ! is_number "$deletion_threshold"; then
    error "deletion_threshold value" "${deletion_threshold}" "is invalid. It should be a number >=0"
  fi

  # Check Moved Threshold
  if [[ -z "${moved_threshold}" ]]; then
    log "WARNING: moved_threshold not defined in snapraid-daily.conf - Using 100 by default"
    moved_threshold=100
  elif ! is_number "$moved_threshold"; then
    error "moved_threshold value" "${moved_threshold}" "is invalid. It should be a number >=0"
  fi

  # Check Updated Threshold
  if [[ -z "${updated_threshold}" ]]; then
    log "WARNING: updated_threshold not defined in snapraid-daily.conf - Using 100 by default"
    updated_threshold=100
  elif ! is_number "$updated_threshold"; then
    error "updated_threshold value" "${updated_threshold}" "is invalid. It should be a number >=0"
  fi

  # Check for a Scrub Percent. default to 8%, sanity check its between 0 and 100
  if [[ -z "${scrub_percent}" ]]; then
    log "WARNING: scrub_percent is not defined snapraid-daily.conf - Using 8%"
    scrub_percent=8
  elif ! is_valid_scrub_percent_number "$scrub_percent"; then
    error "scrub-percent value:" "$scrub_percent" "is invalid - It should be a number between 0.0 and 100.0 with Up to One Decimal Place - Exiting"
  fi

  # Check for a Scrub Age, default to 21 days, sanity check its not negative
  if [[ -z "${scrub_age}" ]]; then
    log "WARNING: scrub_age is not defined in snapraid-daily.conf - Using 21 days"
    scrub_age=21
  elif ! is_number "$scrub_age"; then
    error "scrub_age value:" "$scrub_age" "is invalid - It should be a number >=0"
  elif [[ $scrub_age -lt 0 ]]; then
    error "scrub_age cannot be a negative number - Exiting"
  fi

  # Check for disable_emails_on_success, default to no. Sanity check it's "yes" or "no"
  if [[ -z "${disable_emails_on_success}" ]]; then
    disable_emails_on_success="no"
  elif [[ "${disable_emails_on_success}" != "yes" && "${disable_emails_on_success}" != "no" ]]; then
    error "Specified invalid disable_emails_on_success in config - It should be either \"yes\" or \"no\""
  elif [[ "${disable_emails_on_success}" == "yes" ]]; then
    log "INFO: Notification Emails & Hook(s) disabled on Success"
  fi

  # Check for include_diff_in_email, default to no. Sanity check it's "yes" or "no"
  if [[ -z "${include_diff_in_email}" ]]; then
    include_diff_in_email="no"
  elif [[ "${include_diff_in_email}" != "yes" && "${include_diff_in_email}" != "no" ]]; then
    error "Specified invalid include_diff_in_email in config file - It should be either \"yes\" or \"no\""
  fi

  # Check for sync_pre_hash, default to yes. Sanity check it's "yes" or "no"
  if [[ -z "${sync_pre_hash}" ]]; then
    sync_pre_hash="yes"
  elif [[ "${sync_pre_hash}" != "yes" && "${sync_pre_hash}" != "no" ]]; then
    error "Specified invalid sync_pre_hash in config file - It should be either \"yes\" or \"no\""
  fi

  # Check for force_zero & if set with input args. Default to no if undefined - exit if invalid
  if [[ "${force_zero_arg}" == "yes" ]]; then
    force_zero="yes"
  elif [[ -z "${force_zero}" ]]; then
    force_zero="no"
  elif [[ "${force_zero}" != "yes" && "${force_zero}" != "no" ]]; then
    error "Specified invalid force_zero in config - It should be either \"yes\" or \"no\""
  fi

  # Check for force_empty & if set with input args. Default to no if undefined - exit if invalid
  if [[ "${force_empty_arg}" == "yes" ]]; then
    force_empty="yes"
  elif [[ -z "${force_empty}" ]]; then
    force_empty="no"
  elif [[ "${force_empty}" != "yes" && "${force_empty}" != "no" ]]; then
    error "Specified invalid force_empty in config file - It should be either \"yes\" or \"no\""
  fi

  # Check for force_uuid & if set with input args. Default to no if undefined - exit if invalid
  if [[ "${force_uuid_arg}" == "yes" ]]; then
    force_uuid="yes"
  elif [[ -z "${force_uuid}" ]]; then
    force_uuid="no"
  elif [[ "${force_uuid}" != "yes" && "${force_uuid}" != "no" ]]; then
    error "Specified invalid force_uuid in config file - It should be either \"yes\" or \"no\""
  fi

  # Check for force_nocopy & if set with input args. Default to no if undefined - exit if invalid
  if [[ "${force_nocopy_arg}" == "yes" ]]; then
    force_nocopy="yes"
  elif [[ -z "${force_nocopy}" ]]; then
    force_nocopy="no"
  elif [[ "${force_nocopy}" != "yes" && "${force_nocopy}" != "no" ]]; then
    error "Specified invalid force_nocopy in config file - It should be either \"yes\" or \"no\""
  fi

  # Check for disable_update_check parameter. If undefined - default it to disabled
  if [[ -z "${disable_update_check}" ]]; then
    disable_update_check="no"
  elif [[ "${disable_update_check}" != "yes" && "${disable_update_check}" != "no" ]]; then
    error "Specified invalid disable_update_check in config file - It should be either \"yes\" or \"no\""
  fi

  # SMART Report (Off by default)
  if [[ -z "${smart_report}" ]]; then
    smart_report="no"
  elif [[ "${smart_report}" != "yes" && "${smart_report}" != "no" ]]; then
    error "Specified invalid smart_report in config file - It should be either \"yes\" or \"no\""
  fi

  # Spin Down Disks (Off by default)
  if [[ -z "${spin_down_disks}" ]]; then
    spin_down_disks="no"
  elif [[ "${spin_down_disks}" != "yes" && "${spin_down_disks}" != "no" ]]; then
    error "Specified invalid spin_down_disks in config file - It should be either \"yes\" or \"no\""
  fi
  
  # Check Start/End/Notfication hooks to see if they are defined
  get_number_of_hooks "start_hook"
  get_number_of_hooks "end_hook"
  get_number_of_hooks "notification_hook"
}

# Check for Update via Github Page if not disabled in the config and if curl is installed
check_for_update() {
  update_available="no"
  if [[ "${disable_update_check}" == "no" ]] && is_installed curl; then
    local_script_version="$(sed 's/\.//g;s/~//;s/beta[0-9]*//' <<<"${version}")"
    if github_version=$(curl --silent --retry 3 "${github_version_file}"); then
      github_script_version="$(sed 's/\.//g;s/~//;s/beta[0-9]*//' <<<"${github_version}")"
      if is_number "${github_script_version}" && [[ "${github_script_version}" -gt "${local_script_version}" ]]; then
        update_available="yes"
      fi
    else
      log "WARNING: Contacting ${github_page} for an update failed..."
    fi
  fi
}

# Sanity Check for Dependencies
check_dependencies() {
  if [[ -n "${snapraid_binary_path}" ]]; then
    if [[ ! -x "${snapraid_binary_path}" ]]; then
      error "SnapRAID Binary Path: ${snapraid_binary_path} in Config File does not exist or is not Executable"
    else
      log "INFO: SnapRAID Binary Path: ${snapraid_binary_path}"
    fi
  else
    if ! is_installed snapraid; then
      error "SnapRAID is not installed or not found in \$PATH"
    else
      snapraid_binary_path="$(command -v snapraid)"
    fi
  fi

  # Check all dependencies - Disable emails if mutt is not installed or in $PATH
  local dependencies=( "grep" "tee" "awk" "sed" "mktemp" "date" "dirname" "readlink" "whoami")
  for cmd in "${dependencies[@]}"; do
    if ! is_installed "${cmd}"; then error "${cmd} not installed or found in \$PATH - Exiting..."; fi
  done
  if ! is_installed mutt; then
    log "WARNING: mutt command not found in \$PATH - No emails will be sent"
    enable_emails="no"
  fi
  log ""
}

# Print a condensed help message for a quick start
print_help() {
  log ""
  log "Usage: snapraid-daily         [OPTIONS...]"
  log ""
  log "  -s, --sync-only             Only Sync the Array - Do not run Scrub"
  log ""
  log "  -c, --scrub-only            Only Scrub the Array - Do not run Sync"
  log "                              Note that if both of these options are omitted, the"
  log "                              default is to run sync and then scrub. They also can"
  log "                              not be specified at the same time"
  log ""
  log "  -o, --override-thresholds   Ignore the deletion/moved thresholds to force a sync"
  log ""
  log "  -f, --config [path-to-conf] Override default config file. Could be useful if one"
  log "                              has multiple snapraid arrays to manage on the same system"
  log ""
  log "  -d, --disable-touch         Disable the touch operation. Can be useful to bypass"
  log "                              expected touch errors. Where for example files were"
  log "                              recently removed from the array."
  log ""
  log "  -q, --quiet                 Suppress the output of the touch, diff, sync and scrub"
  log "                              commands for snapraid. The final status message is still"
  log "                              displayed as normal."
  log ""
  log "  -i, --ignore-user           The script does a check that all SnapRAID content files"
  log "                              are owned by the user running the script and will exit"
  log "                              if any are not. This option bypasses this check and"
  log "                              continues regardless if they are owned by a different"
  log "                              user."
  log ""
  log "  -h, --help                  Print help"
  log ""
  log "Extra Sync Options: Included for Edge Cases, but not usually recommended or needed"
  log ""
  log "  -fz, --force-zero           Run Sync with --force-zero active."
  log ""
  log "  -fe, --force-empty          Run Sync with --force-empty active. Useful"
  log ""
  log "  -fu, --force-uuid           Run Sync with --force-uuid active."
  log ""
  log "  -fn, --force-nocopy         Run Sync with --force-nocopy active."
  log ""
  log "Manual Entries:"
  log "  Main Script:                snapraid-daily(1)      $ man snapraid-daily"
  log "  Config File:                snapraid-daily.conf(1) $ man snapraid-daily.conf"
  log ""
  exit $success_code
}

# Function to Parse Input Arguments to the Script - Unset variables 1st
parse_arguments() {

  # Check for valid input arguments
  while (( ${#} )); do
    case "${1}" in

      # Check for Sync Only
      -s|--sync-only)
        sync_only="yes"
      ;;

      # Check for Scrub Only
      -c|--scrub-only)
        scrub_only="yes"
      ;;

      # Check for Override Thresholds
      -o|--override-thresholds)
        override_thresholds="yes"
      ;;

      # Check for Quiet Option
      -q|--quiet)
        quiet_option="yes"
      ;;

      # Check if the default config is overriden, also check if the file is empty or doesn't exist
      -f|--config)
        shift 1
        if (( $# == 0 )); then
          log "ERROR: Specified custom config file, but none given - Exiting"
          print_help
        elif [[ ! -f "${1}" ]]; then
          log "ERROR: Specified custom config file, but given file does not exist - Exiting"
          print_help
        else
          custom_config_file="${1}"
        fi
      ;;

      # Disable Touch
      -d|--disable-touch)
        disable_touch="yes"
      ;;

      # Ignore Script User
      -i|--ignore-user)
        ignore_script_user="yes"
      ;;

      # Check for Help
      -h|--help)
        print_help
      ;;

      # Check for Force Zero
      -fz|--force-zero)
        force_zero_arg="yes"
      ;;

      # Check for Force Empty
      -fe|--force-empty)
        force_empty_arg="yes"
      ;;

      # Check for Force UUID
      -fu|--force-uuid)
        force_uuid_arg="yes"
      ;;

      # Check for Force No-Copy
      -fn|--force-nocopy)
        force_nocopy_arg="yes"
      ;;

      # Check for an Unrecognised Argument
      *)
        log "Invalid Input Argument:" "${1}"
        log ""
        print_help
      ;;
    esac
    shift 1
  done

  # Check if any of the above argument variables were not defined
  if [[ -z "${sync_only}" ]]; then sync_only="no"; fi
  if [[ -z "${scrub_only}" ]]; then scrub_only="no"; fi
  if [[ -z "${override_thresholds}" ]]; then override_thresholds="no"; fi
  if [[ -z "${quiet_option}" ]]; then quiet_option="no"; fi
  if [[ -z "${disable_touch}" ]]; then disable_touch="no"; fi
  if [[ -z "${ignore_script_user}" ]]; then ignore_script_user="no"; fi
  if [[ -z "${force_zero_arg}" ]]; then force_zero_arg="no"; fi
  if [[ -z "${force_empty_arg}" ]]; then force_empty_arg="no"; fi
  if [[ -z "${force_uuid_arg}" ]]; then force_uuid_arg="no"; fi
  if [[ -z "${force_nocopy_arg}" ]]; then force_nocopy_arg="no"; fi

  # Check if --sync-only and --scrub-only were specified at the same time - Exit if so
  if [[ $sync_only == "yes" && $scrub_only == "yes" ]]; then
    log "-s|--sync-only & -c|--scrub-only arguments can't both be specified at the same time - Exiting"
    log ""
    print_help
  fi

  # Check if --override-thresholds and --scrub-only were specified at the same - Warn if so
  if [[ $scrub_only == "yes" && $override_thresholds == "yes" ]]; then
    log "WARNING: -o|--override-thresholds has no effect when using -c|--scrub-only"
  fi
}

# Print Greeting in Email Log
print_greeting() {

  # Get the SnapRAID Version, The Hostname and the OS Name
  if snapraid_output=$("${snapraid_binary_path}" -V); then
    snapraid_version="$(awk '{gsub(/v/,""); print $3}' <<< "${snapraid_output}")"
  fi
  if is_installed hostname; then
    system_hostname=$(hostname --fqdn) &> "/dev/null"
  fi
  if [[ -f "/etc/os-release" ]]; then
    os_name=$(awk -F \" '/^PRETTY_NAME=/ {print $2}' "/etc/os-release")
  fi

  # Print Greeting
  log_to_email "##############################"
  log_to_email "# SnapRAID-DAILY Version:" "${version}"
  log_to_email "##############################"
  if [[ "${update_available}" == "yes" ]]; then
    log_to_email "# Update Available at ${github_page}/releases"
    log_to_email "##############################"
  fi
  log_to_email "Initialized at $(date +%H:%M:%S) on $(date +%d/%m/%Y)"
  if [[ -n "${system_hostname}" ]]; then log_to_email " * Hostname:" "${system_hostname}"; fi
  if [[ -n "${os_name}" ]]; then log_to_email " * Host OS:" "${os_name}"; fi
  if [[ -n "${snapraid_version}" ]]; then log_to_email " * SnapRAID Version:" "$snapraid_version"; fi
  log_to_email "Input Options:"

  # Print out if the user has disabled the Touch Operation
  if [[ "${disable_touch}" == "yes" ]]; then
    log_to_email " * Disable Touch: YES"
  else
    log_to_email " * Disable Touch: NO"
  fi

  # Print Out all Sync Related Parameters if Sync is being Ran
  if [[ "${sync_only}" == "yes" || ( "${sync_only}" == "no" && "${scrub_only}" == "no" ) ]]; then
    log_to_email " * Run-Sync: YES"
    if [[ "${sync_pre_hash}" == "yes" ]]; then
      log_to_email " * Sync Pre-Hash: YES"
    else
      log_to_email " * Sync Pre-Hash: NO"
    fi
    if [[ "${force_zero}" == "yes" ]]; then 
      log_to_email " * Sync Force-Zero: YES"
    fi 
    if [[ "${force_empty}" == "yes" ]]; then
      log_to_email " * Sync Force-Empty: YES"
    fi
    if [[ "${force_uuid}" == "yes" ]]; then
      log_to_email " * Sync Force-UUID: YES"
    fi 
    if [[ "${force_nocopy}" == "yes" ]]; then
      log_to_email " * Sync Force-No-Copy: YES"
    fi 
  else
    log_to_email " * Run-Sync: NO"
  fi

  # Print Out all Scrub Releated Parameters if Scrub is being Ran
  if [[ "${scrub_only}" == "yes" || ( "${sync_only}" == "no" && "${scrub_only}" == "no" ) ]]; then
    log_to_email " * Run-Scrub: YES"
    log_to_email " * Scrub-Percent:" $scrub_percent
    log_to_email " * Scrub-Age:" $scrub_age "days and older"
  else
    log_to_email " * Run-Scrub: NO"
  fi

  # Check if the Override Thresholds has been specified
  if [[ "${override_thresholds}" == "yes" ]]; then
    log_to_email " * Override Thresholds: YES"
  else
    log_to_email " * Override Thresholds: NO"
  fi

  # Print Thresholds
  if [[ $deletion_threshold == 0 ]]; then
    log_to_email " * Deletion Threshold: Disabled"
  else
    log_to_email " * Deletion Threshold:" $deletion_threshold
  fi
  if [[ $moved_threshold == 0 ]]; then
    log_to_email " * Moved/Relocated Threshold: Disabled"
  else
    log_to_email " * Moved/Relocated Threshold:" $moved_threshold
  fi
  if [[ $updated_threshold == 0 ]]; then
    log_to_email " * Updated Threshold: Disabled"
  else
    log_to_email " * Updated Threshold:" $updated_threshold
  fi

  # Print SMART Report and Disk Spin Down Options if being used
  if [[ "${smart_report}" == "yes" ]]; then
    log_to_email " * SMART Report: YES"
  else
    log_to_email " * SMART Report: NO"
  fi
  if [[ "${spin_down_disks}" == "yes" ]]; then
    log_to_email " * Spin-Down HDDs: YES"
  else
    log_to_email " * Spin-Down HDDs: NO"
  fi

  # Print out if the Quiet Option is being used
  if [[ $quiet_option == "yes" ]]; then
    log_to_email " * Quiet Output: YES"
  else
    log_to_email " * Quiet Output: NO"
  fi

  # Specify if the Check for Updates is disabled or not
  if [[ "${disable_update_check}" == "yes" ]]; then
    log_to_email " * Check for Updates: NO"
  else
    log_to_email " * Check for Updates: YES"
  fi

  # Check if the Emails are Enabled or not
  if [[ "${enable_emails}" == "yes" ]]; then
    log_to_email " * Emails Enabled: YES"
  else
    log_to_email " * Emails Enabled: NO"
  fi

  # Print out if the Differences are being Included in the Email Report or Not
  if [[ "${include_diff_in_email}" == "yes" ]]; then
    log_to_email " * Include Differences in Email: YES"
  else
    log_to_email " * Include Differences in Email: NO"
  fi

  # Print out whether the Emails/Calls to the Notification hook are disable
  if [[ "${disable_emails_on_success}" == "yes" ]]; then
    log_to_email " * Emails/Notification Hook(s) on Success: YES"
  else
    log_to_email " * Emails/Notification Hook(s) on Success: YES"
  fi
    
  # Print Start and Stop Hooks if Being Used
  if [[ -n "${start_hook1:-}" || -n "${end_hook1:-}" || -n "${notification_hook1:-}" ]]; then
    log_to_email "Hooks:"
    if [[ -n "${start_hook1:-}" ]]; then
      log_to_email " * Start-Hook: YES ($N_start_hooks)"
    else
      log_to_email " * Start-Hook: NO"
    fi
    if [[ -n "${end_hook1:-}" ]]; then
      log_to_email " * End-Hook: YES ($N_end_hooks)"
    else
      log_to_email " * End-Hook: NO"
    fi
    if [[ -n "${notification_hook1:-}" ]]; then
      log_to_email " * Notification Hook: YES ($N_notification_hooks)"
    else
      log_to_email " * Notification Hook: NO"
    fi
  else
    log_to_email "Hooks: NONE"
  fi
  log_to_email "Run-Log is Below:"
  log_to_email ""
}

# Inital Check - Do an initial check of the array check for errors/sync in progress etc.
initial_status_check() {
  log_to_email "##############################"
  log_to_email "# SnapRAID-DAILY: Initial Status Check"
  log_to_email "##############################"

  # Check all Content Files are found
  log_to_email_time "Script User: $(whoami)"
  if [[ "${ignore_script_user}" == "yes" ]]; then log_to_email_time "Ignoring Content Files owner..."; fi
  check_content_files_exist
  log_to_email_time "All Content Files found"
  log_to_email_time "Checking current status..."

  # Call snapraid status
  snapraid_status_cmd

  # Check Exit Status & Number of Files Requiring Touch
  status_exit_code=$(awk -F ":" '/^summary:exit:/ {print $3}' "${status_command_logfile}")
  touch_required_count=$(awk -F ":" '/^summary:zerosubsecond_file_count:/ {print $3}' "${status_command_logfile}")

  # Scenario 1 - Check if Snapraid is Already in Use - Exit if so
  if grep -qw "SnapRAID is already in use!" "${status_command_logfile}"; then
    log_to_email_time "SnapRAID is already Use - Exiting..."
    log_to_email ""
    notify_of_warning "SnapRAID-DAILY: SnapRAID In Use!"
    clean_up_logfiles
    exit $already_in_use_code
  
  # Scenario 2 - Check if the important parameters above are not defined
  elif [[ -z "${status_exit_code}" || -z "${touch_required_count}" ]]; then
    log_to_email_time "Unexpected Status Output - Exiting..."
    log_to_email_time "Status Exit Code:" "${status_exit_code}"
    log_to_email_time "Status Logfile is attached"
    log_to_email ""
    notify_of_warning "SnapRAID-DAILY: Initial Error(s) Present" "${status_command_logfile}" include_status
    clean_up_logfiles
    exit $error_code

  # Scenario 3 - Check if a Sync is unfinished, stop for scrub-only otherwise continue
  elif [[ "${status_exit_code}" == "unsynced" ]]; then
    if [[ "${scrub_only}" == "no" ]]; then
      log_to_email_time "Sync Already in Progress"
      log_to_email_time "Status Exit Code:" "${status_exit_code}"
      log_to_email_time "Continuing..." 
    else
      log_to_email_time "Sync Already in Progress but Scrub-Only is selected"
      log_to_email_time "Status Exit Code:" "${status_exit_code}"
      log_to_email_time "Cannot Scrub unless sync is finished - Exiting..."
      log_to_email_time "Status Logfile is attached"
      log_to_email ""
      notify_of_warning "SnapRAID-DAILY: Sync In Progress" "${status_command_logfile}" include_status
      clean_up_logfiles
      exit $error_code
    fi

  # Scenario 4 - Check for errors - Exit if present
  elif [[ "${status_exit_code}" == "bad" ]]; then
    log_to_email_time "Found error(s) - Exiting..."
    log_to_email_time "Status Exit Code:" "${status_exit_code}"
    log_to_email_time "Status Logfile is attached"
    log_to_email ""
    notify_of_warning "SnapRAID-DAILY: Initial Error(s) Present" "${status_command_logfile}" include_status
    clean_up_logfiles
    exit $error_code

  # Scenario 5 - None of the above checks found anything - Continue to Sync/Scrub
  elif [[ "${status_exit_code}" == "ok" ]]; then
    log_to_email_time "No Issues Found in Initial Check"
    log_to_email_time "Status Exit Code:" "${status_exit_code}"
    log_to_email_time "Ready to run SnapRAID operations"

  # Scenario 6 - Status Exit Code is not "ok", "bad" or "unsynced" (should be impossible)
  else
    log_to_email_time "Unexpected Status Exit Code - Exiting..."
    log_to_email_time "Status Exit Code:" "${status_exit_code}"
    log_to_email_time "Status Logfile is attached"
    log_to_email ""
    notify_of_warning "SnapRAID-DAILY: Initial Error(s) Present" "${status_command_logfile}" include_status
    clean_up_logfiles
    exit $error_code
  fi

  # Check if Touch is Needed and if Scrub Only is Not Selected
  if [[ "${scrub_only}" == "no" && $touch_required_count != 0 ]]; then
    log_to_email_time "Touch Required on $touch_required_count files..."
    touch_required="yes"
  else
    log_to_email_time "Touch Not Needed..."
    touch_required="no"
  fi
  log_to_email ""
}

# Touch Function - Run touch if required (and scrub only is not selected)
run_touch_if_needed() {
  if [[ "${touch_required}" == "yes" && "${disable_touch}" == "no" ]]; then
    log_to_email "##############################"
    log_to_email "# SnapRAID-DAILY: Touch"
    log_to_email "##############################"
    log_to_email_time "Starting Touch..."

    # Call Snapraid touch command. Use return code (log tags limited for touch)
    if ! snapraid_touch_cmd; then
      log_to_email_time "Touch Encountered Issues - Please Investigate..."
      log_to_email_time "Touch Command Logfile is attached"
      log_to_email_time "If expected, re-run the script with the -d or --disable-touch option to continue."
      log_to_email ""
      run_end_hooks
      notify_of_warning "SnapRAID-DAILY: Touch Warning(s)" "${touch_command_logfile}" include_status
      clean_up_logfiles
      exit $error_code
    else
      log_to_email_time "Touch Completed on $touch_required_count files"
      log_to_email ""
    fi
  fi
}

# Check for Changes, Deletion Threshold & Move Threshold
check_array_for_changes_and_thresholds() {
  log_to_email "##############################"
  log_to_email "# SnapRAID-DAILY: Difference Check"
  log_to_email "##############################"
  log_to_email_time "Checking array for changes..."

  # Call snapraid diff command
  snapraid_diff_cmd

  # Copy the diff command logfile so it can be used to record the sync changes later
  if [[ "${include_diff_in_email}" == "yes" ]]; then
    cp "${diff_command_logfile}" "${sync_changes_log}" 
  fi

  # Check the Exit Status of the Diff Command to see if a sync is required or not
  # Since Version 14.0, also need to consider the "unsynced" status
  if [[ "${diff_exit_status}" == "diff" || "${diff_exit_status}" == "unsynced" ]]; then

    # Specify a Sync is Required
    sync_required="yes"
    log_to_email_time "Changes Detected"
    log_to_email " * Equal: $number_equal"
    log_to_email " * Added: $number_added"
    log_to_email " * Removed: $number_removed"
    log_to_email " * Updated: $number_updated"
    log_to_email " * Moved: $number_moved"
    log_to_email " * Copied: $number_copied"
    log_to_email " * Relocated: $number_relocated"
    log_to_email " * Restored: $number_restored"

    # Check For Deletion/Moved Thresholds
    if [[ $override_thresholds == "yes" ]]; then
      log_to_email_time "Overriding Deletion/Moved/Updated Thresholds"
      log_to_email_time "Proceeding to sync regardless..."

    # Check For Either Threshold being greater than zero AND exceeded...
    # For moves consider both the number moved AND relocated
    elif [[ ($number_removed -gt $deletion_threshold && $deletion_threshold -gt 0)  || \
            ($((number_moved+number_relocated)) -gt $moved_threshold && $moved_threshold -gt 0) || \
            ($number_updated -gt $updated_threshold && $updated_threshold -gt 0) ]]
    then 
      log_to_email ""
      log_to_email_time "One or more Thresholds Exceeded"
      log_to_email " * Deleted: $number_removed"
      log_to_email " * Moved/Relocated: $((number_moved+number_relocated))"
      log_to_email " * Updated: $number_updated"

      # Print Whether Thresholds have been disabled or not
      if [[ $deletion_threshold -gt 0 ]]; then
        log_to_email " * Deletion Threshold: $deletion_threshold"
      else
        log_to_email " * Deletion Threshold: Disabled" 
      fi
      if [[ $moved_threshold -gt 0 ]]; then
      log_to_email " * Moved/Relocated Threshold: $moved_threshold"
      else
        log_to_email " * Moved/Relocated Threshold: Disabled"
      fi
      if [[ $updated_threshold -gt 0 ]]; then
       log_to_email " * Updated Threshold: $updated_threshold"
      else
        log_to_email " * Updated Threshold: Disabled"
      fi
      log_to_email "Maybe a Sync is not a good idea?..."
      log_to_email_time "Stopping..."
      log_to_email_time "Diff Command Logfile is attached."
      log_to_email ""
      run_end_hooks
      notify_of_warning "SnapRAID-DAILY: Threshold(s) Exceeded" "${diff_command_logfile}"
      clean_up_logfiles
      exit $thresholds_exceeded_code

    # Sync Regardless if an Unfinished Sync was Found
    elif [[ "${diff_exit_status}" == "unsynced" ]]; then
      log_to_email_time "Sync still in progress - Continuing to Sync..."

    # Otherwise Thresholds were not exceeded and no sync was in progress
    else
      log_to_email_time "No Threshold(s) Exceeded"
      log_to_email_time "Proceeding to sync..."
    fi
    log_to_email ""

  # If the exit status of the diff command is "equal", there are no changes
  elif [[ "${diff_exit_status}" == "equal" ]]; then
    log_to_email_time "No Changes - Nothing to Sync"
    log_to_email ""
    sync_required="no"
  fi
}

# Sync Array Function
sync_array() {
  if [[ "${sync_required}" == "yes" ]]; then
    log_to_email "##############################"
    log_to_email "# SnapRAID-DAILY: Sync"
    log_to_email "##############################"

    # Find the Current Time to Get the Time the Sync was Started At
    sync_start_seconds=$(date +%s)
    log_to_email_time "Starting Sync on $(date +%d/%m/%Y)..."

    # Call snapraid sync command
    snapraid_sync_cmd

    # Compute the Run-Time of the Sync Command for the Email
    sync_finish_seconds=$(date +%s)
    sync_runtime=$((sync_finish_seconds-sync_start_seconds))
    sync_runtime_hours=$((sync_runtime / 3600))
    sync_runtime_minutes=$(( (sync_runtime % 3600) / 60 ))
    sync_runtime_seconds=$(( (sync_runtime % 3600) % 60 ))
    log_to_email_time "Sync Completed on $(date +%d/%m/%Y)"
    log_to_email_time "Duration: $sync_runtime_hours hours, $sync_runtime_minutes minutes, $sync_runtime_seconds seconds"

    # Get Error counts and Exit status from Sync Command Logfile. Consider hash errors if using sync_pre_hash
    io_errors=$(awk -F ":" '/^summary:error_io:/ {print $3}' "${sync_command_logfile}")
    data_errors=$(awk -F ":" '/^summary:error_data:/ {print $3}' "${sync_command_logfile}")
    soft_errors=$(awk -F ":" '/^summary:error_soft:/ {print $3}' "${sync_command_logfile}")
    if [[ "${sync_pre_hash}" == "yes" ]]; then
      hash_errors=$(awk -F ":" '/^hash_summary:error_soft:/ {print $3}' "${sync_command_logfile}")
    fi
    sync_exit_status=$(awk -F ":" '/^summary:exit:/ {print $3}' "${sync_command_logfile}")

    # The File number is referenced multiple times throughout the log - pick the 1st one
    total_file_number=$(awk -F ":" '/^content_info:file:/ {print $3; exit}' "${sync_command_logfile}")
    equal_file_number=$(awk -F ":" '/^summary:equal:/ {print $3}' "${sync_command_logfile}")

    # 1. Check to see if Files were modified during the sync - Exit if so
    if grep -qw "WARNING! You cannot modify files" "${sync_command_logfile}" ; then 
      log_to_email_time "Sync - File(s) Modified During Sync"
      log_to_email " * I/O Errors: $io_errors"
      log_to_email " * Data Errors: $data_errors"
      log_to_email " * Soft Errors: $soft_errors"
      if [[ "${sync_pre_hash}" == "yes" && "${force_nocopy}" == "no" ]]; then
        log_to_email " * Hash Errors: $hash_errors"
      fi
      log_to_email_time "Sync Output Log is attached..."
      log_to_email ""
      run_end_hooks
      notify_of_warning "SnapRAID-DAILY: File(s) Modified during Sync" "${sync_command_logfile}" include_status
      clean_up_logfiles
      exit $files_modified_during_sync_code

    # 2: Check for any undefined parameters - exit if so. Only consider hash errors if not using sync_pre_hash and force_nocopy
    elif [[ -z "${io_errors}" || -z "${data_errors}" || -z "${soft_errors}" || -z "${sync_exit_status}" || -z "${total_file_number}" || \
            -z "${equal_file_number}" || ("${sync_pre_hash}" == "yes" && "${force_nocopy}" == "no" && -z "${hash_errors}") ]]
    then
      log_to_email_time "Unexpected Output from Sync - Please Investigate"
      log_to_email " * I/O Errors: $io_errors"
      log_to_email " * Data Errors: $data_errors"
      log_to_email " * Soft Errors: $soft_errors"
      if [[ "${sync_pre_hash}" == "yes" && "${force_nocopy}" == "no" ]]; then
        log_to_email " * Hash Errors: $hash_errors"
      fi
      log_to_email_time "Sync Output Log is attached..."
      log_to_email ""
      run_end_hooks
      notify_of_warning "SnapRAID-DAILY: Sync Warning(s)" "${sync_command_logfile}" include_status
      clean_up_logfiles
      exit $error_code

    # 3: Exit if any of the number of errors above are non-zero or if the exit status is unexpected
    elif [[ $io_errors != 0  ||  $data_errors != 0  ||  $soft_errors != 0  ||  "${sync_exit_status}" != "ok" || \
          ("${sync_pre_hash}" == "yes" && "${force_nocopy}" == "no" && $hash_errors != 0) ]]
    then
      log_to_email_time "Sync Log Reports Error(s) - Please Investigate"
      log_to_email " * I/O Errors: $io_errors"
      log_to_email " * Data Errors: $data_errors"
      log_to_email " * Soft Errors: $soft_errors"
      if [[ "${sync_pre_hash}" == "yes" && "${force_nocopy}" == "no" ]]; then
        log_to_email " * Hash Errors: $hash_errors"
      fi
      log_to_email " * Exit Status:" "${sync_exit_status}"
      log_to_email_time "Sync Output Log is attached..."
      log_to_email ""
      run_end_hooks
      notify_of_warning "SnapRAID-DAILY: Sync Warning(s)" "${sync_command_logfile}" include_status
      clean_up_logfiles
      exit $error_code

    # 4: Sync Diff exit status reported no changes
    elif [[ "${total_file_number}" == "${equal_file_number}" ]]; then
      log_to_email_time "Found nothing to sync"
      log_to_email ""

    # 5. Otherwise if none of the above checks found anything - The sync was successful
    else
      # Print Out the Changes to Email Output
      log_to_email_time "Sync was Successful"
      log_to_email " * I/O Errors: $io_errors"
      log_to_email " * Data Errors: $data_errors"
      log_to_email " * Soft Errors: $soft_errors"
      if [[ "${sync_pre_hash}" == "yes" && "${force_nocopy}" == "no" ]]; then
        log_to_email " * Hash Errors: $hash_errors"
      fi
      log_to_email " * Exit Status:" "${sync_exit_status}"
      log_to_email_time "Array Changes Found & Updated:"
      log_to_email " * Added: $number_added"
      log_to_email " * Removed: $number_removed"
      log_to_email " * Updated: $number_updated"
      log_to_email " * Moved: $number_moved"
      log_to_email " * Copied: $number_copied"
      log_to_email " * Relocated: $number_copied"
      log_to_email " * Restored: $number_restored"
      log_to_email ""
    fi
  fi
}

# Scrub Array Function
scrub_array() {
  log_to_email "##############################"
  log_to_email "# SnapRAID-DAILY: Scrub"
  log_to_email "##############################"

  # Need to check the array is up to date. More relevant if --scrub-only is selected
  log_to_email_time "Checking if Array is still up to date..."
  snapraid_diff_cmd

  # Copy the diff command logfile so it can be used to record the sync changes later
  if [[ "${include_diff_in_email}" == "yes" ]]; then
    cp "${diff_command_logfile}" "${scrub_changes_log}" 
  fi

  # Check if there are no Moved, Removed, Relocated or Updated Files. Added or Copied are OK for scrubbing
  if [[ $number_removed == 0 && $number_updated == 0 && $number_moved == 0 && $number_relocated == 0 ]]; then
    # Array is still up to date - proceeding to scrub
    log_to_email_time "Array is Up-to-Date - Proceeding"

    # Find the Current Time to Get the Time the Sync was Started At
    scrub_start_seconds=$(date +%s)
    log_to_email_time "Starting Scrub on $(date +%d/%m/%Y)"
    log_to_email_time "Scrubbing $scrub_percent% older than $scrub_age days..."

    # Call Snapraid Scrub command
    snapraid_scrub_cmd

    # Compute the Run-Time of the Scrub Command
    scrub_finish_seconds=$(date +%s)
    scrub_runtime=$((scrub_finish_seconds-scrub_start_seconds))
    scrub_runtime_hours=$((scrub_runtime / 3600))
    scrub_runtime_minutes=$(( (scrub_runtime % 3600) / 60 ))
    scrub_runtime_seconds=$(( (scrub_runtime % 3600) % 60 ))
    log_to_email_time "Scrub Completed at $(date +%d/%m/%Y)"
    log_to_email_time "Duration: $scrub_runtime_hours hours, $scrub_runtime_minutes minutes, $scrub_runtime_seconds seconds"

    # Check Scrub Command Logfile for Errors
    scrub_io_errors=$(awk -F ":" '/^summary:error_io:/ {print $3}' "${scrub_command_logfile}")
    scrub_data_errors=$(awk -F ":" '/^summary:error_data:/ {print $3}' "${scrub_command_logfile}")
    scrub_soft_errors=$(awk -F ":" '/^summary:error_soft:/ {print $3}' "${scrub_command_logfile}")
    scrub_exit_status=$(awk -F ":" '/^summary:exit/ {print $3}' "${scrub_command_logfile}")

    # 1: Check if Nothing was found to scrub
    if grep -qw "Nothing to scrub" "${scrub_command_logfile}"; then
      log_to_email_time "Found Nothing to Scrub"
      log_to_email ""
      nothing_to_scrub="yes"

    # 2: Check if any of the above error counts or exit status are undefined
    elif [[ -z "${scrub_io_errors}" || -z "${scrub_data_errors}" || -z "${scrub_soft_errors}" || -z "${scrub_exit_status}" ]]; then
      log_to_email_time "Unexpected output from Scrub - Please Investigate"
      log_to_email " * I/O Errors: $scrub_io_errors"
      log_to_email " * Data Errors: $scrub_data_errors"
      log_to_email " * Soft Errors: $scrub_soft_errors"
      log_to_email " * Exit Status: ${scrub_exit_status}"
      log_to_email_time "Scrub Output Log is attached..."
      log_to_email ""
      run_end_hooks
      notify_of_warning "SnapRAID-DAILY: Scrub Warning(s)" "${scrub_command_logfile}" include_status
      clean_up_logfiles
      exit $error_code

    # 3: Check if any of the number of errors in the counts above are non-zero
    elif [[ $scrub_io_errors != 0 || $scrub_data_errors != 0 || $scrub_soft_errors != 0 || "${scrub_exit_status}" != "ok" ]]; then
      log_to_email_time "Scrub Log Reports Error(s) - Please Investigate"
      log_to_email " * I/O Errors: $scrub_io_errors"
      log_to_email " * Data Errors: $scrub_data_errors"
      log_to_email " * Soft Errors: $scrub_soft_errors"
      log_to_email " * Exit Status: ${scrub_exit_status}"
      log_to_email_time "Scrub Output Log is attached..."
      log_to_email ""
      run_end_hooks
      notify_of_warning "SnapRAID-DAILY: Scrub Warning(s)" "${scrub_command_logfile}" include_status
      clean_up_logfiles
      exit $error_code

    # 4: Otherwise the scrub was successful
    else
      log_to_email_time "Scrub was successful"
      log_to_email " * I/O Errors: $scrub_io_errors"
      log_to_email " * Data Errors: $scrub_data_errors"
      log_to_email " * Soft Errors: $scrub_soft_errors"
      log_to_email " * Exit Status: ${scrub_exit_status}"
      log_to_email_time "Scrubbed $scrub_percent% older than $scrub_age days"
      log_to_email ""
      nothing_to_scrub="no"
    fi
  else
    # Array is not up to date and can't be scrubbed without the risk of an error
    log_to_email_time "Array not up-to-date - Sync Required"
    log_to_email_time "Changes detected are:"
    log_to_email " * Equal: $number_equal"
    log_to_email " * Added: $number_added"
    log_to_email " * Removed: $number_removed"
    log_to_email " * Updated: $number_updated"
    log_to_email " * Moved: $number_moved"
    log_to_email " * Copied: $number_copied"
    log_to_email " * Relocated: $number_relocated"
    log_to_email " * Restored: $number_restored"
    log_to_email_time "Cannot Proceed with Scrub - Stopping"
    log_to_email_time "Diff Command Logfile is attached."
    log_to_email ""
    run_end_hooks
    notify_of_warning "SnapRAID-DAILY: Sync Required" "${diff_command_logfile}" include_status
    clean_up_logfiles
    exit $error_code
  fi
}

# Get the number of start, end and notification hooks defined in the configuration file
get_number_of_hooks() {
  local N_hooks=0

  # Loop Through Defined Hooks in Config File to find out how many are defined
  for ((i=1; i<=max_hooks+1; i++)); do
    local hook="${1}"$i

    # Check the hook script exists and is executable
    if [[ -n "${!hook:-}" && -x "${!hook:-}" ]]; then
      N_hooks=$((N_hooks+1))

      # Check if the max number of suppVorted hooks has been reached
      if [[ $i -gt $max_hooks ]]; then
        log "WARNING: Only $max_hooks are supported, ignoring above numbered \"${1}\" hooks"
        if [[ "${1}" == "start_hook" ]]; then
          N_start_hooks=$max_hooks
        elif [[ "${1}" == "end_hook" ]]; then
          N_end_hooks=$max_hooks
        elif [[ "${1}" == "notification_hook" ]]; then
          N_notification_hooks=$max_hooks
        fi
        # Return 0 to exit the function and avoid setting the number of hooks below
        return 0
      fi

      # Print that the Hook was found
      if [[ "${1}" == "start_hook" ]]; then
        log "INFO: Start Hook $i: ${!hook}"
      elif [[ "${1}" == "end_hook" ]]; then
        log "INFO: End Hook $i: ${!hook}"
      elif [[ "${1}" == "notification_hook" ]]; then
        log "INFO: Notification Hook $i: ${!hook}"
      fi

    # Otherwise exit if it is not executable or doesn't exist
    elif [[ -n "${!hook:-}" && ! -x "${!hook:-}" ]]; then
      error "${1}$i defined in config file: ${!hook} does not exist or is not executable - Exiting"
    # Otherwise Break
    else
      break
    fi
  done

  # Set the Hook Number depending on 1st argument
  if [[ "${1}" == "start_hook" ]]; then
    N_start_hooks=$N_hooks
  elif [[ "${1}" == "end_hook" ]]; then
    N_end_hooks=$N_hooks
  elif [[ "${1}" == "notification_hook" ]]; then
    N_notification_hooks=$N_hooks
  fi
}

# Call Start Hook(s)
run_start_hooks() {
  # Run the Start Hook Directly if it was specified in the config file
  if [[ $N_start_hooks != 0 ]]; then
    log_to_email "##############################"
    log_to_email "# SnapRAID-DAILY: Start Hook(s)"
    log_to_email "##############################"

    # Loop through each start hook
    for ((i=1; i<=N_start_hooks; i++)); do
      local start_hook="start_hook"$i
      log_to_email_time "Calling Start Hook $i/$N_start_hooks..."

      # Run Start Hook & Check Error Code
      if ! "${!start_hook}" "start"; then
        log_to_email_time "Start Hook $i/$N_start_hooks ended in error"
        log_to_email ""
        notify_of_warning "SnapRAID-DAILY: Start Hook Error(s)"
        clean_up_logfiles
        exit $error_code
      else
        log_to_email_time "Start Hook $i/$N_start_hooks Done"
        # Check all hooks have been completed
        if [[ $i == "$N_start_hooks" ]]; then
          log_to_email_time "All Start Hooks completed successfully"
          log_to_email ""
        else
          log_to_email ""
        fi
      fi
    done
  fi
}

# Call End Hook
run_end_hooks() {
  # Run the End Hook Directly if it was specifed in the config file
  if [[ $N_end_hooks != 0 ]]; then
    log_to_email "##############################"
    log_to_email "# SnapRAID-DAILY: End Hook(s)"
    log_to_email "##############################"
    local error_count=0
 
    # Loop through each end hook
    for ((i=1; i<=N_end_hooks; i++)); do
      local end_hook="end_hook"$i
      log_to_email_time "Calling End Hook $i/$N_end_hooks..."

      # Run End Hook Directly with "end" argument & check error code
      if ! "${!end_hook}" "end"; then
        error_count=$((error_count+1))
        log_to_email_time "End Hook $i/$N_end_hooks ended in error"
        log_to_email ""
      else
        log_to_email_time "End Hook $i/$N_end_hooks Done"
        log_to_email ""
      fi

      # Check all hooks have been completed
      if [[ $i == "$N_end_hooks" && "$error_count" == 0 ]]; then
        log_to_email_time "All End Hooks completed successfully"
        log_to_email ""
        end_hook_errors="no"
      elif [[ $i == "$N_end_hooks" && "$error_count" != 0 ]]; then
        log_to_email_time "One or more errors running End Hook(s)"
        log_to_email ""
        end_hook_errors="yes"
      fi
    done
  else
    end_hook_errors="no"
  fi
}

# Generate SMART Report
generate_smart_report() {
  if [[ "${smart_report}" == "yes" ]]; then
    log_to_email "##############################"
    log_to_email "# SnapRAID-DAILY: SMART Report"
    log_to_email "##############################"
    # Check if the script is running as root, if not see if Sudo is installed...
    if [[ $UID != 0 ]]; then
      if ! is_installed sudo; then
        log_to_email "ERROR: Script not ran as root and sudo is not installed"
        log_to_email "sudo is required to generate the SMART report if not running the script"
        log_to_email "as root."
      else
        snapraid_smart_report "non_root"
      fi
    else
      snapraid_smart_report
    fi    
    log_to_email ""
  fi
}

# Spin Down Disks
spin_down_hdd_disks() {
  if [[ "${spin_down_disks}" == "yes" ]]; then
    log_to_email "##############################"
    log_to_email "# SnapRAID-DAILY: HDD Spin-Down"
    log_to_email "##############################"
    # Check if the Script is running as root, if not see if Sudo is installed
    if [[ $UID != 0 ]]; then
      if ! is_installed sudo; then
        log_to_email "ERROR: Script not ran as root and sudo is not installed"
        log_to_email "sudo is required to spin down the disks if not running the script"
        log_to_email "as root."
      else
        snapraid_spin_down_disks "non_root"
      fi 
    else
      snapraid_spin_down_disks
    fi
    log_to_email ""
  fi
}
 
# Call Notification Hook(s)
run_notification_hooks() {
  if [[ $N_notification_hooks != 0 ]]; then
    local notification_title="${1}"
    local notification_body="${2}"

    # Notification Attachment may not exist
    local notification_attachment="${3:-}"

    # Only run the notification hooks if enabled or in the case of a warning
    if [[ ( "${disable_emails_on_success}" == "no" ) || \
          ( "${disable_emails_on_success}" == "yes" && -n "${notification_attachment}" ) ]]
    then
      log "##############################"
      log "# SnapRAID-DAILY: Notification Hook(s)"
      log "##############################"

      # Loop through all defined hooks
      for ((i=1; i<=N_notification_hooks; i++)); do
        local notification_hook="notification_hook"$i

        # Call the Custom Notification Hook Script if one was given
        if [[ -x "${!notification_hook}" ]]; then
          log " * Calling Notification Hook $i/$N_notification_hooks :" "${!notification_hook}"
          if ! "${!notification_hook}" "${notification_title}" "${notification_body}" "${notification_attachment}"; then
            log " * WARNING: Notification Hook ${notification_hook} returned an error"
          fi
          log ""
        fi
      done
    fi
  fi
}

# Insert File differences into email
include_differences_in_email() {

  # Only do this if include_diff_in_email is set to yes...
  if [[ "${include_diff_in_email}" == "yes" ]]; then
    local diff_changes_log

    # Check if Scrub Only was Set based on Input Options
    if [[ $scrub_only == "yes" ]]; then
      diff_changes_log="${scrub_changes_log}"
    else
      diff_changes_log="${sync_changes_log}"
    fi

    # Only proceed if the file is not empty...
    if [[ -s "${diff_changes_log}" ]]; then

      # Need to get the changes again
      number_equal=$( awk -F ":" '/^summary:equal:/ {print $3}' "${diff_changes_log}")
      number_added=$( awk -F ":" '/^summary:added:/ {print $3}' "${diff_changes_log}")
      number_removed=$( awk -F ":" '/^summary:removed:/ {print $3}' "${diff_changes_log}")
      number_updated=$( awk -F ":" '/^summary:updated:/ {print $3}' "${diff_changes_log}")
      number_moved=$( awk -F ":" '/^summary:moved:/ {print $3}' "${diff_changes_log}")
      number_copied=$( awk -F ":" '/^summary:copied:/ {print $3}' "${diff_changes_log}")
      number_relocated=$( awk -F ":" '/^summary:relocated:/ {print $3}' "${diff_changes_log}")
      number_restored=$( awk -F ":" '/^summary:restored:/ {print $3}' "${diff_changes_log}")

      # Print a Banner and include the changes in the main logfile
      log_to_email ""
      log_to_email "##############################"
      log_to_email "# SnapRAID-DAILY: File Differences"
      log_to_email "##############################"
      if [[ $number_added == 0 && $number_removed == 0 && $number_updated == 0 && $number_moved == 0 && \
            $number_copied == 0 && $number_relocated == 0 && $number_restored == 0 ]]
      then
        log_to_email_time "No Changes since the last sync."
      else
        log_to_email_time "These are the file differences since the last sync."
        log_to_email ""
        log_to_email "Added Files: $number_added"
        if [[ $number_added != 0 ]]; then
          awk '/^scan:add/ { sub(/^scan:/, ""); print }' "${diff_changes_log}" | tee -a "${main_logfile}"
        fi
        log_to_email ""
        log_to_email "Removed Files: $number_removed"
        if [[ $number_removed != 0 ]]; then
          awk '/^scan:remove/ { sub(/^scan:/, ""); print }' "${diff_changes_log}" | tee -a "${main_logfile}"
        fi
        log_to_email ""
        log_to_email "Updated Files: $number_updated"
        if [[ $number_updated != 0 ]]; then
          awk '/^scan:update/ { sub(/^scan:/, ""); print }' "${diff_changes_log}" | tee -a "${main_logfile}"
        fi
        log_to_email ""
        log_to_email "Moved Files: $number_moved"
        if [[ $number_moved != 0 ]]; then
          awk '/^scan:move/ { sub(/^scan:/, ""); print }' "${diff_changes_log}" | tee -a "${main_logfile}"
        fi
        log_to_email ""
        log_to_email "Copied Files: $number_copied"
        if [[ $number_copied != 0 ]]; then
          awk '/^scan:copy/ { sub(/^scan:/, ""); print }' "${diff_changes_log}" | tee -a "${main_logfile}"
        fi
        log_to_email ""
        log_to_email "Relocated Files: $number_relocated"
        if [[ $number_relocated != 0 ]]; then
          awk '/^scan:relocate/ { sub(/^scan:/, ""); print }' "${diff_changes_log}" | tee -a "${main_logfile}"
        fi
        log_to_email ""
        log_to_email "Restored Files: $number_restored"
        if [[ $number_restored != 0 ]]; then
          awk '/^scan:restore/ { sub(/^scan:/, ""); print }' "${diff_changes_log}" | tee -a "${main_logfile}"
        fi
      fi
    fi
  fi
}

# Success Notification
notify_of_success() {

  # Call Snapraid Status to Put the Final Array Status into the Email
  snapraid_status_to_email

  # Figure out the subject for the Notification(s)
  if [[ $sync_only == "yes" ]]; then
    if [[ $sync_required == "yes" ]]; then
      success_subject="SnapRAID-DAILY: Sync OK"
    else
      success_subject="SnapRAID-DAILY: Nothing to Sync"
    fi
  elif [[ $scrub_only == "yes" ]]
  then
    if [[ $nothing_to_scrub == "yes" ]]; then
      success_subject="SnapRAID-DAILY: Nothing to Scrub"
    else
      success_subject="SnapRAID-DAILY: Scrub OK"
    fi
  else
    if [[ $sync_required == "no" && $nothing_to_scrub == "yes" ]]; then
      success_subject="SnapRAID-DAILY: Nothing to Sync OR Scrub"
    else
      success_subject="SnapRAID-DAILY: All OK"
    fi
  fi

  # Print Success Banner here
  if [[ "${end_hook_errors}" == "no" ]]; then
    log_to_email "##############################"
    log_to_email "# SnapRAID-DAILY Result: SUCCESS"
    log_to_email "##############################"
  else
    log_to_email "##############################"
    log_to_email "# SnapRAID-DAILY Result: WARNING(S)"
    log_to_email "##############################"
  fi

  # Insert Differences into Email Logfile if Enabled
  include_differences_in_email

  # Send the Success Email
  if [[ "${disable_emails_on_success}" == "no" && "${enable_emails}" == "yes" ]]; then
    send_email "${success_subject}"
  fi

  # Call the Custom Notification Hook Script if one was given
  run_notification_hooks "${success_subject}" "${main_logfile}"
}

# Warning Notification
notify_of_warning() {
  local subject="${1}"
  local attachment="${2:-}"
  local status="${3:-}"

  # Include the output of the status command in the email if required
  if [[ -n "${status}" ]]; then
    snapraid_status_to_email
  fi

  # Print Warning Banner here
  log_to_email "##############################"
  log_to_email "# SnapRAID-DAILY Result: WARNING(S)"
  log_to_email "##############################"

  # Insert Differences into Email Logfile if Enabled
  include_differences_in_email

  # Send Email Notification if Emails are Enabled and include attachment if present
  if [[ $enable_emails == "yes" && -n "${attachment}" ]]; then
    send_email "${subject}" "${attachment}"
  elif [[ $enable_emails == "yes" && -z "${attachment}" ]]; then
    send_email "${subject}"
  fi

  # If Custom Notification Hook are present - Call them here
  if [[ -z "${attachment}" ]]; then
    run_notification_hooks "${subject}" "${main_logfile}"
  else
    run_notification_hooks "${subject}" "${main_logfile}" "${attachment}"
  fi
}

# Send Emails using mutt 
send_email() {
  local email_subject="${1}"

  # Email Attachment may not exist...
  local email_attachment="${2:-}"

  # Add the Hostname as a Signature to the Emails
  if [[ -n "${system_hostname}" ]]; then
    log_to_email "" &>"/dev/null"
    log_to_email "Regards," &>"/dev/null"
    log_to_email "${system_hostname}" &>"/dev/null"
    log ""
  fi

  # Generate mutt args
  mutt_args=( -F "${muttrc_path}" -s "${email_subject}" )
  if [[ -n "${email_attachment:-}" ]]; then
    mutt_args+=( -a "${email_attachment}" -- )
  fi

  # Call mutt to send the email
  log "Emailing ${email_address}..."
  if mutt "${mutt_args[@]}" "${email_address}" < "${main_logfile}"; then
    log "Email Sent Successfully"
    log ""
  else
    log "Problem Sending Email"
    log ""
  fi
}

# Clean Up Log-Files Function
clean_up_logfiles() {
  log "Removing /tmp files..."
  local logfiles=( "${main_logfile}" "${status_command_logfile}" "${scrub_command_logfile}" \
                "${sync_command_logfile}" "${touch_command_logfile}" "${diff_command_logfile}" \
                "${main_logfile_without_diff}" "${sync_changes_log}" "${scrub_changes_log}")
  for file in "${logfiles[@]}"; do
    rm -f -- "${file}" &>"/dev/null"
  done
}

###################################################
# CALL MAIN FUNCTION
###################################################
main "$@"

