#!/usr/bin/env bash

# Simple bash script example to stop and restart
# a number of services.

# Specify List of Services here
services=( "smbd" "sonarr" "radarr" "lidarr" "readarr" "bazarr")

# Check for Root
if [[ $UID != 0 ]]; then
  echo "ERROR: Script should be ran as root - exiting"
fi

# Get Number of Services specified above
N_Services=${#services[@]}

# Start Section
if [[ "${1}" == "start" ]]; then
  for ((i=0; i<=N_Services-1; i++ )); do
    # Check The Service exists
    if [[ ! -f "/etc/systemd/system/${services[$i]}.service" && \
          ! -f "/lib/systemd/system/${services[$i]}.service" && \
          ! -f "/usr/lib/systemd/system/${services[$i]}.service" ]]; then
      echo "WARNING: Service unit files do not exist for" "${services[$i]}"
      continue
    fi

    # Stop Service Using systemctl
    if ! systemctl stop "${services[$i]}"; then
      echo "ERROR stopping" "${services[$i]}" "service"
    else
      echo "Stopped" "${services[$i]}"
    fi
  done
fi

# End Section
if [[ "${1}" == "end" ]]; then
  for ((i=0; i<=N_Services-1; i++)); do
    # Check The Service exists
    if [[ ! -f "/etc/systemd/system/${services[$i]}.service" && \
          ! -f "/lib/systemd/system/${services[$i]}.service" && \
          ! -f "/usr/lib/systemd/system/${services[$i]}.service" ]]; then
      echo "WARNING: Service unit files do not exist for" "${services[$i]}"
      continue
    fi

    # Start Service Using systemctl
    if ! systemctl start "${services[$i]}"; then
      echo "ERROR starting" "${services[$i]}" "service"
    else
      echo "Started" "${services[$i]}"
    fi
  done
fi

