#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

# Prompt the User for a User Name and Group
# to run the service as. Use the values defined in
# debian/templates

# Prompt for the User
db_input high snapraid-daily/systemd_user || true
db_go

# Prompt for the Group
db_input high snapraid-daily/systemd_group || true
db_go

