#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule
db_version 2.0

# Purge the debconf values only
action="$1"

if [ "$action" = "purge" ]
then
  db_purge
fi

# Exit with Success
exit 0

